export const location = [
  "Alappuzha",
  "Ernakulam",
  "Kozhikode",
  "Palakkad",
  "Kollam",
  "Kannur",
  "Kasaragod",
  "Idukki",
  "Kottayam",
  "Thrissur",
"  Pathanamthitta",
"  Malappuram",
  "Wayanad",
  "Thiruvananthapuram",
]
